#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ErrorLog.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Logga/Details.cshtml")]
    public partial class _Views_Logga_Details_cshtml : System.Web.Mvc.WebViewPage<Logga.Models.ErrorLogEntry>
    {
        public _Views_Logga_Details_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"portlet blue-chambray box\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"portlet-title\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n\t\t\t\t\t<i");

WriteLiteral(" class=\"fa fa-cogs\"");

WriteLiteral("></i>\r\n                </div>\r\n\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 15 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.DateError));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 18 "..\..\Views\Logga\Details.cshtml"
                   Write(Model.DateError);

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 23 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.Source));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 26 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.Source));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 31 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.Target));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 34 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.Target));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 39 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 42 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 47 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.User));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 50 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.User));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n\t\t\t\t<div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 55 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.Host));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t\t<div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("\t\t\t\t\t\t");

            
            #line 58 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.Host));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t</div>\r\n\t\t\t\t</div>\r\n                <div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 63 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 66 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 71 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.InnerException));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 74 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.InnerException));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"row static-info\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"col-md-5 name\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 79 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayNameFor(model => model.StackTrace));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"col-md-7 value\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 82 "..\..\Views\Logga\Details.cshtml"
                   Write(Html.DisplayFor(model => model.StackTrace));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div" +
">\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
