#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ErrorLog.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Logga/Details.cshtml")]
    public partial class _Views_Logga_Details_cshtml : System.Web.Mvc.WebViewPage<Logga.Data.LoggaEntry>
    {
        public _Views_Logga_Details_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Logga\Details.cshtml"
  
    Layout = null;

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<!DOCTYPE html>\r\n<html>\r\n<head>\r\n    <title>Hi, I\'m Logga and i\'m your friend" +
"!</title>\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css\"");

WriteLiteral(">\r\n    <script");

WriteLiteral(" src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js\"");

WriteLiteral("></script>\r\n</head>\r\n\r\n<body");

WriteLiteral(" bgcolor=\"white\"");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"navbar navbar-default navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"navbar-header\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\".navbar-collapse\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Logga\Details.cshtml"
           Write(Html.ActionLink("Back to Index", "Index", "Logga", new { area = "" }, new { @class = "navbar-brand" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n    <br /><br />\r\n    <span>\r\n " +
"       <h1>Server Error in \'/\' Application.<hr");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" size=\"1\"");

WriteLiteral(" color=\"silver\"");

WriteLiteral("></h1>\r\n\r\n        ");

WriteLiteral("\r\n    </span>\r\n\r\n    <font");

WriteLiteral(" face=\"Arial, Helvetica, Geneva, SunSans-Regular, sans-serif \"");

WriteLiteral(">\r\n\r\n        <b> Description: </b>\r\n");

WriteLiteral("        ");

            
            #line 39 "..\..\Views\Logga\Details.cshtml"
   Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br /><br />\r\n\r\n        <b> Exception Details: </b>");

            
            #line 42 "..\..\Views\Logga\Details.cshtml"
                              Write(Model.Type);

            
            #line default
            #line hidden
WriteLiteral(": ");

            
            #line 42 "..\..\Views\Logga\Details.cshtml"
                                           Write(Model.Message);

            
            #line default
            #line hidden
WriteLiteral("<br>\r\n\r\n        ");

WriteLiteral("\r\n\r\n        <br>\r\n\r\n        <b> Source File: </b> ");

            
            #line 66 "..\..\Views\Logga\Details.cshtml"
                         Write(Model.Target);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br><br>\r\n\r\n        <b>Stack Trace:</b>\r\n\r\n        <table");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" bgcolor=\"#ffffcc\"");

WriteLiteral(">\r\n            <tbody>\r\n                <tr>\r\n                    <td>\r\n         " +
"               <pre>\r\n");

WriteLiteral("                             ");

            
            #line 76 "..\..\Views\Logga\Details.cshtml"
                        Write(Model.StackTrace);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </pre>\r\n                    </td>\r\n                " +
"</tr>\r\n            </tbody>\r\n        </table>\r\n\r\n        <br>\r\n        <b>Date:<" +
"/b>&nbsp;");

            
            #line 84 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.DateError);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br /><br>\r\n\r\n        <b>User:</b>&nbsp;");

            
            #line 87 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.User);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br /><br>\r\n\r\n        <b>Host:</b>&nbsp;");

            
            #line 90 "..\..\Views\Logga\Details.cshtml"
                     Write(Model.Host);

            
            #line default
            #line hidden
WriteLiteral("\r\n        <br /><br>\r\n    </font>\r\n</body>\r\n</html>\r\n");

        }
    }
}
#pragma warning restore 1591
