#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using ErrorLog.Core;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Logga/Index.cshtml")]
    public partial class _Views_Logga_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Logga.Models.ErrorLogEntry>>
    {
        public _Views_Logga_Index_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n\t<div");

WriteLiteral(" class=\"col-md-12\"");

WriteLiteral(">\r\n\t\t<div");

WriteLiteral(" class=\"portlet light\"");

WriteLiteral(">\r\n\t\t\t<div");

WriteLiteral(" class=\"portlet-title\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"caption\"");

WriteLiteral(">\r\n\t\t\t\t</div>\r\n\t\t\t\t");

WriteLiteral("\r\n\t\t\t</div>\r\n\t\t\t<div");

WriteLiteral(" class=\"portlet-body\"");

WriteLiteral(">\r\n\t\t\t\t<div");

WriteLiteral(" class=\"table-container\"");

WriteLiteral(">\r\n\t\t\t\t\t<table");

WriteLiteral(" class=\"table table-striped table-bordered table-hover dataTable no-footer\"");

WriteLiteral(">\r\n\t\t\t\t\t\t<thead>\r\n\t\t\t\t\t\t\t<tr>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 19 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.DateError));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 22 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.Source));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 25 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.Target));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 28 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.Type));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 31 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.User));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th>\r\n");

WriteLiteral("\t\t\t\t\t\t\t\t\t");

            
            #line 34 "..\..\Views\Logga\Index.cshtml"
                               Write(Html.DisplayNameFor(model => model.Host));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t\t\t\t\t\t\t</th>\r\n\t\t\t\t\t\t\t\t<th></th>\r\n\t\t\t\t\t\t\t</tr>\r\n\t\t\t\t\t\t</thead>\r\n\t\t\t\t\t\t<tbody>\r\n" +
"\t\t\t\t\t\t");

WriteLiteral("\r\n\r\n\t\t\t\t\t\t</tbody>\r\n\t\t\t\t\t</table>\r\n\t\t\t\t</div>\r\n\t\t\t</div>\r\n\t\t</div>\r\n\t</div>\r\n</di" +
"v>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 75 "..\..\Views\Logga\Index.cshtml"
Write(Scripts.Render("~/bundles/datatables"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <script>\r\n        jQuery(document).ready(function () {\r\n            $(\'ta" +
"ble\').DataTable({\r\n                \"paging\": false,\r\n                \"language\":" +
" {\r\n                    \"url\": \"");

            
            #line 82 "..\..\Views\Logga\Index.cshtml"
                       Write(Url.Action("DatatableJson"));

            
            #line default
            #line hidden
WriteLiteral("\"\r\n                }\r\n            });\r\n        });\r\n    </script>\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
